language: python
python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7

install: python setup.py develop
script:
  - python setup.py test
  - python setup.py pep8
  - cd project
  - pip install -r requirements.txt
  - python setup.py test
