language: python
python:
  - 3.5
  - 3.4
  - 3.3
  - 2.7

install: python setup.py develop
script:
  - python setup.py test
  - python setup.py pep8
  - cd project
  - pip install -r requirements.txt
  - python setup.py test
  - cd ..

deploy:
  provider: pypi
  user: jbouzekri
  password:
    secure: opR5VuOUjc6iTMkrTvOdi89LGnL1gIEranAwxFUPPDQo1XiIIsbT1H9HgjacmFCO5myN4Ay20sPkAfVzasidtUdbXLWRQAVOaFiY/SX73Am6y/c9APtKQtzKwQ1Vcl+hvQ9q22UuRKghoKOrdq3bUdg5nInIKCBkBs5KphUv9WG7gTDIrCwzu2HijNcrvKKMfTwxW1h1IfWgXei+P15RsmCqaroxzDu1/5m3l7eRClJX4EgK6CQTSstoTAPN96hPFQoIW+h8CiwlO0bFK3hOnt9Qp+uUeEKTu2P5VBVC+oGAEI3eGjeSPQuRtma93aVmSyHQc4SjCkMpxpWbvy8Mud1yk1vHF/J5+ThmmA/zilhxHCQ+3jKYfY4AiMDdfn/KcBCcoNrkzNDwKvZhpPn4nqAexeGEBo+a12mXhzXOqNAGj9D7yVmKmlk5LNdUIBnRr1p92fWtNheeQTuw770Tmg8qpPviwsOaTDvFeEJrdtnQuqiul7BykLdQD/QX/vxULP3sWfwCAcJ+c6TYqjVcqs9FG/ui1OzAL/aRFdqpYf2mMyn8L9Z2WyFZgfi4Lt908KDRSQ+KrLVZO9JGeH2wbg4EYuqS/vzrQjzqCKLAhMHZSs56bu9AGi796MyVilP8ht9T6Rk4seJ5S7IU/msszBiJnrJvM6C6LLf8cgktrVg=
  on:
    tags: true
    distributions: sdist bdist_wheel bdist_egg
    repo: weenect/weedi
